# EDA

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from pathlib import Path

In [2]:
# PATHS
PROJECT_PATH = Path("../").resolve()
DATA_PATH = PROJECT_PATH / "data"
DATA_FEATURES_PATH = DATA_PATH / "NUSW-NB15_features.csv"
DATA_TESTING_PATH = DATA_PATH / "UNSW_NB15_testing-set.csv"
DATA_TRAINING_SET_PATH = DATA_PATH / "UNSW_NB15_training-set.csv"
DATA_1_PATH = DATA_PATH / "UNSW-NB15_1.csv"
DATA_2_PATH = DATA_PATH / "UNSW-NB15_2.csv"
DATA_3_PATH = DATA_PATH / "UNSW-NB15_3.csv"
DATA_4_PATH = DATA_PATH / "UNSW-NB15_4.csv"
DATA_LIST_EVENTS_PATH = DATA_PATH / "UNSW-NB15_LIST_EVENTS.csv"

## Chargement des dataset

In [3]:
df_data_features = pd.read_csv(DATA_FEATURES_PATH, encoding="cp1252")
df_data_features.head(len(df_data_features))

,No.,Name,Type,Description
0,1,srcip,nominal,Source IP address
1,2,sport,integer,Source port number
2,3,dstip,nominal,Destination IP address
3,4,dsport,integer,Destination port number
4,5,proto,nominal,Transaction protocol
5,6,state,nominal,Indicates to the state and its dependent proto...
6,7,dur,Float,Record total duration
7,8,sbytes,Integer,Source to destination transaction bytes
8,9,dbytes,Integer,Destination to source transaction bytes
9,10,sttl,Integer,Source to destination time to live value
10,11,dttl,Integer,Destination to source time to live value
11,12,sloss,Integer,Source packets retransmitted or dropped
12,13,dloss,Integer,Destination packets retransmitted or dropped
13,14,service,nominal,"http, ftp, smtp, ssh, dns, ftp-data ,irc and ..."
14,15,Sload,Float,Source bits per second
15,16,Dload,Float,Destination bits per second
16,17,Spkts,integer,Source to destination packet count
17,18,Dpkts,integer,Destination to source packet count
18,19,swin,integer,Source TCP window advertisement value
19,20,dwin,integer,Destination TCP window advertisement value
20,21,stcpb,integer,Source TCP base sequence number
21,22,dtcpb,integer,Destination TCP base sequence number
22,23,smeansz,integer,Mean of the ?ow packet size transmitted by the...
23,24,dmeansz,integer,Mean of the ?ow packet size transmitted by the...
24,25,trans_depth,integer,Represents the pipelined depth into the connec...
25,26,res_bdy_len,integer,Actual uncompressed content size of the data t...
26,27,Sjit,Float,Source jitter (mSec)
27,28,Djit,Float,Destination jitter (mSec)
28,29,Stime,Timestamp,record start time
29,30,Ltime,Timestamp,record last time
30,31,Sintpkt,Float,Source interpacket arrival time (mSec)
31,32,Dintpkt,Float,Destination interpacket arrival time (mSec)
32,33,tcprtt,Float,"TCP connection setup round-trip time, the sum ..."
33,34,synack,Float,"TCP connection setup time, the time between th..."
34,35,ackdat,Float,"TCP connection setup time, the time between th..."
35,36,is_sm_ips_ports,Binary,If source (1) and destination (3)IP addresses ...
36,37,ct_state_ttl,Integer,No. for each state (6) according to specific r...
37,38,ct_flw_http_mthd,Integer,No. of flows that has methods such as Get and ...
38,39,is_ftp_login,Binary,If the ftp session is accessed by user and pas...
39,40,ct_ftp_cmd,integer,No of flows that has a command in ftp session.
40,41,ct_srv_src,integer,No. of connections that contain the same servi...
41,42,ct_srv_dst,integer,No. of connections that contain the same servi...
42,43,ct_dst_ltm,integer,No. of connections of the same destination add...
43,44,ct_src_ ltm,integer,No. of connections of the same source address ...
44,45,ct_src_dport_ltm,integer,No of connections of the same source address (...
45,46,ct_dst_sport_ltm,integer,No of connections of the same destination addr...
46,47,ct_dst_src_ltm,integer,No of connections of the same source (1) and t...
47,48,attack_cat,nominal,The name of each attack category. In this data...
48,49,Label,binary,0 for normal and 1 for attack records

Le dataset "NUSW-NB15_features.csv" contient les noms, types et descriptions des features.

In [4]:
df_data_training_set = pd.read_csv(DATA_TRAINING_SET_PATH, encoding="cp1252")
df_data_training_set.head()

,ï»¿id,dur,proto,service,state,spkts,dpkts,sbytes,dbytes,rate,...,ct_dst_sport_ltm,ct_dst_src_ltm,is_ftp_login,ct_ftp_cmd,ct_flw_http_mthd,ct_src_ltm,ct_srv_dst,is_sm_ips_ports,attack_cat,label
0,1,0.000011,udp,-,INT,2,0,496,0,90909.0902,...,1,2,0,0,0,1,2,0,Normal,0
1,2,0.000008,udp,-,INT,2,0,1762,0,125000.0003,...,1,2,0,0,0,1,2,0,Normal,0
2,3,0.000005,udp,-,INT,2,0,1068,0,200000.0051,...,1,3,0,0,0,1,3,0,Normal,0
3,4,0.000006,udp,-,INT,2,0,900,0,166666.6608,...,1,3,0,0,0,2,3,0,Normal,0
4,5,0.000010,udp,-,INT,2,0,2126,0,100000.0025,...,1,3,0,0,0,2,3,0,Normal,0

Le dataset "NUSW-NB15_training-set.csv" est le jeu d'entraînement sur lequel nous entraîneront les algorithmes de clusterisation.

In [5]:
print(
    f"Dimension du dataset training-set : {df_data_training_set.shape[0]} lignes et {df_data_training_set.shape[1]} colonnes"
)

Dimension du dataset training-set : 82332 lignes et 45 colonnes

In [6]:
def compare_columns(df1, df2, name1="df1", name2="df2"):
    cols1 = set([c.lower() for c in df1.columns])
    cols2 = set([c.lower() for c in df2.columns])

    only_in_df1 = cols1 - cols2
    only_in_df2 = cols2 - cols1
    common = cols1 & cols2

    print(f"\nColonnes uniquement dans {name1} ({len(only_in_df1)}):")
    print(sorted(only_in_df1))

    print(f"\nColonnes uniquement dans {name2} ({len(only_in_df2)}):")
    print(sorted(only_in_df2))

    print(f"\nColonnes communes ({len(common)}):")
    print(sorted(common))

    return {"only_in_df1": only_in_df1, "only_in_df2": only_in_df2, "common": common}


_ = compare_columns(
    df_data_features.set_index("Name").T,
    df_data_training_set,
    name1="df_data_features",
    name2="df_data_training_set",
)

Colonnes uniquement dans df_data_features (12):
['ct_src_ ltm', 'dintpkt', 'dmeansz', 'dsport', 'dstip', 'ltime', 'res_bdy_len', 'sintpkt', 'smeansz', 'sport', 'srcip', 'stime']

Colonnes uniquement dans df_data_training_set (8):
['ct_src_ltm', 'dinpkt', 'dmean', 'rate', 'response_body_len', 'sinpkt', 'smean', 'ï»¿id']

Colonnes communes (37):
['ackdat', 'attack_cat', 'ct_dst_ltm', 'ct_dst_sport_ltm', 'ct_dst_src_ltm', 'ct_flw_http_mthd', 'ct_ftp_cmd', 'ct_src_dport_ltm', 'ct_srv_dst', 'ct_srv_src', 'ct_state_ttl', 'dbytes', 'djit', 'dload', 'dloss', 'dpkts', 'dtcpb', 'dttl', 'dur', 'dwin', 'is_ftp_login', 'is_sm_ips_ports', 'label', 'proto', 'sbytes', 'service', 'sjit', 'sload', 'sloss', 'spkts', 'state', 'stcpb', 'sttl', 'swin', 'synack', 'tcprtt', 'trans_depth']

* Colonnes aux nom similaires :

| df_data_features |df_data_training_set |
| :- | :- |
| 'ct_src_ ltm' | 'ct_src_ltm' |
| 'dintpkt' | 'dinpkt' |
| 'dmeansz' | 'dmean' |
| 'res_bdy_len' | 'response_body_len' |
| 'sintpkt' | 'sinpkt' |
| 'smeansz' | 'smean' |

* Features non présentes dans le dataset training_set : 'dsport', 'dstip', 'ltime', 'sport', 'srcip', 'stime'.
* Colonnes non présentes dans les features : 'rate' et 'ï»¿id'.

In [8]:
df_data_training_set = pd.read_csv(DATA_LIST_EVENTS_PATH, encoding="cp1252")
df_data_training_set.head()

  Attack category Attack subcategory  Number of events
0          normal                NaN           2218761
1        Fuzzers                 FTP               558
2        Fuzzers                HTTP              1497
3        Fuzzers                 RIP              3550
4        Fuzzers                 SMB              5245

Le dataset "NUSW-NB15_LIST_EVENTS.csv" présente la répartition des attaques.